---
title: "Analysis of Weekly Newsletters: Initial Report"
author: "Alvin Sheng"
output: pdf_document
---

The open percentage is 

$$\mathrm{Open \ \%} = \frac{\mathrm{number \ of \ contacts \ who \ opened \ the \ email}}{\mathrm{number \ of \ contacts \ sent \ to}} \times 100\%$$

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(ggplot2)
library(scales)
library(lubridate)
```

```{r}
load("wrangled_data/weeklies1.RData")
```

# Summary Statistics over Time, 2019-2020

```{r}
ggplot(data = weeklies1, aes(x = datetime, y = contacts_sent_to)) + 
  geom_point() + 
  ggtitle("Number of Contacts Sent To over Time, 2019-2020") + 
  xlab("Month") +
  ylab("Number of Contacts Sent To") +
  geom_smooth() +
  scale_x_datetime(labels = date_format("%m/%y"), 
               breaks = date_breaks("2 month"))
  
```

When did the pandemic start changing things? The March 12 weekly newsletter was the first one to mention the COVID-19 pandemic and remote volunteering opportunities. 

```{r}
ggplot(data = weeklies1, aes(x = datetime, y = opened, col = covid)) + 
  geom_point() + 
  ggtitle("Open Percentage over Time, 2019-2020") + 
  xlab("Month") +
  ylab("Open Percentage") +
  geom_smooth() +
  scale_x_datetime(labels = date_format("%m/%y"), 
               breaks = date_breaks("2 month")) + 
  geom_vline(xintercept = as.POSIXct("2020-03-01"), col = "red")
  
```

There is a spike in the open percentages after March. 



```{r}
ggplot(data = weeklies1, aes(x = datetime, y = clicks, col = covid)) + 
  geom_point() + 
  ggtitle("Click Percentage over Time, 2019-2020") + 
  xlab("Month") +
  ylab("Click Percentage") +
  geom_smooth() +
  scale_x_datetime(labels = date_format("%m/%y"), 
               breaks = date_breaks("2 month")) + 
  geom_vline(xintercept = as.POSIXct("2020-03-01"), col = "red")
```



```{r}
ggplot(data = weeklies1, aes(x = datetime, y = unsubscribes, col = covid)) + 
  geom_point() + 
  ggtitle("Unsubscribe Percentage over Time, 2019-2020") + 
  xlab("Month") +
  ylab("Unsubscribe Percentage") +
  geom_smooth() +
  scale_x_datetime(labels = date_format("%m/%y"), 
               breaks = date_breaks("2 month")) + 
  geom_vline(xintercept = as.POSIXct("2020-03-01"), col = "red")
```



# Summary Statistics throughout a Day

```{r}
# extracting the time
# this sets all the dates to 2021-01-10
daytime <- as.POSIXct(format(weeklies1$datetime, format="%H:%M"),
                    tz = "America/New_York", format = "%H:%M")
```

```{r}
weeklies_before <- weeklies1[weeklies1$covid == "Before",]
weeklies_after <- weeklies1[weeklies1$covid == "After",]
```

<!-- ```{r} -->
<!-- ggplot(data = weeklies_after, aes(x = mins_since_midnight, y = opened)) +  -->
<!--   geom_point() +  -->
<!--   ggtitle("Open Percentage throughout a Day") +  -->
<!--   xlab("Time") + -->
<!--   ylab("Open %") + -->
<!--   geom_smooth() #+ -->
<!--   #scale_x_datetime(labels = date_format("%m/%y"),  -->
<!--                #breaks = date_breaks("2 month")) -->
<!-- ``` -->

```{r}
ggplot(data = weeklies1, aes(x = daytime, y = opened, col = covid)) + 
  geom_point() + 
  ggtitle("Open Percentage throughout a Day") + 
  xlab("Time") +
  ylab("Open %") +
  geom_smooth(aes(group = 1)) # +
  # scale_x_datetime(breaks = date_breaks("1 hour"), labels = date_format("%H:%M"))
```

There may be a slight upward trend. 



<!-- Explore the precise time newsletters were sent--morning, noon, evening -->






<!-- Repeat for monthly donor newsletters -->




